In [1]:
import numpy as np

In [2]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sb

In [3]:
from sklearn.model_selection import train_test_split

In [4]:
df = pd.read_csv("CarPrice_Assignment.csv")

In [5]:
df.head()

,car_ID,symboling,CarName,fueltype,aspiration,doornumber,carbody,drivewheel,enginelocation,wheelbase,...,enginesize,fuelsystem,boreratio,stroke,compressionratio,horsepower,peakrpm,citympg,highwaympg,price
0,1,3,alfa-romero giulia,gas,std,two,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111,5000,21,27,13495.0
1,2,3,alfa-romero stelvio,gas,std,two,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111,5000,21,27,16500.0
2,3,1,alfa-romero Quadrifoglio,gas,std,two,hatchback,rwd,front,94.5,...,152,mpfi,2.68,3.47,9.0,154,5000,19,26,16500.0
3,4,2,audi 100 ls,gas,std,four,sedan,fwd,front,99.8,...,109,mpfi,3.19,3.40,10.0,102,5500,24,30,13950.0
4,5,2,audi 100ls,gas,std,four,sedan,4wd,front,99.4,...,136,mpfi,3.19,3.40,8.0,115,5500,18,22,17450.0

In [25]:
df[["curbweight"]]

     curbweight
0          2548
1          2548
2          2823
3          2337
4          2824
..          ...
200        2952
201        3049
202        3012
203        3217
204        3062

[205 rows x 1 columns]

In [6]:
df.drop("car_ID", axis=1, inplace=True)

In [7]:
df.drop("CarName", axis=1, inplace=True)

In [8]:
df.drop("carbody", axis=1, inplace=True)

In [9]:
df.head()

,symboling,fueltype,aspiration,doornumber,drivewheel,enginelocation,wheelbase,carlength,carwidth,carheight,...,enginesize,fuelsystem,boreratio,stroke,compressionratio,horsepower,peakrpm,citympg,highwaympg,price
0,3,gas,std,two,rwd,front,88.6,168.8,64.1,48.8,...,130,mpfi,3.47,2.68,9.0,111,5000,21,27,13495.0
1,3,gas,std,two,rwd,front,88.6,168.8,64.1,48.8,...,130,mpfi,3.47,2.68,9.0,111,5000,21,27,16500.0
2,1,gas,std,two,rwd,front,94.5,171.2,65.5,52.4,...,152,mpfi,2.68,3.47,9.0,154,5000,19,26,16500.0
3,2,gas,std,four,fwd,front,99.8,176.6,66.2,54.3,...,109,mpfi,3.19,3.40,10.0,102,5500,24,30,13950.0
4,2,gas,std,four,4wd,front,99.4,176.6,66.4,54.3,...,136,mpfi,3.19,3.40,8.0,115,5500,18,22,17450.0

In [10]:
df["fueltype_gas/diesel"] = df["fueltype"].apply(lambda x: 1 if x == "diesel" else 0)

In [11]:
df["aspiration_std/turbo"] = df["fueltype"].apply(lambda x: 1 if x == "turbo" else 0)

In [12]:
df["drivewheel_rwd/fwd/4wd"] = df["drivewheel"]

In [13]:
df["drivewheel_rwd/fwd/4wd"] = df["drivewheel_rwd/fwd/4wd"].replace({"rwd":0, "fwd":1, "4wd":2})

/var/folders/95/wj31kgsj4wg535xg7yn89djc0000gn/T/ipykernel_11096/358587081.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df["drivewheel_rwd/fwd/4wd"] = df["drivewheel_rwd/fwd/4wd"].replace({"rwd":0, "fwd":1, "4wd":2})

In [14]:
df.head()

,symboling,fueltype,aspiration,doornumber,drivewheel,enginelocation,wheelbase,carlength,carwidth,carheight,...,stroke,compressionratio,horsepower,peakrpm,citympg,highwaympg,price,fueltype_gas/diesel,aspiration_std/turbo,drivewheel_rwd/fwd/4wd
0,3,gas,std,two,rwd,front,88.6,168.8,64.1,48.8,...,2.68,9.0,111,5000,21,27,13495.0,0,0,0
1,3,gas,std,two,rwd,front,88.6,168.8,64.1,48.8,...,2.68,9.0,111,5000,21,27,16500.0,0,0,0
2,1,gas,std,two,rwd,front,94.5,171.2,65.5,52.4,...,3.47,9.0,154,5000,19,26,16500.0,0,0,0
3,2,gas,std,four,fwd,front,99.8,176.6,66.2,54.3,...,3.40,10.0,102,5500,24,30,13950.0,0,0,1
4,2,gas,std,four,4wd,front,99.4,176.6,66.4,54.3,...,3.40,8.0,115,5500,18,22,17450.0,0,0,2

In [15]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 205 entries, 0 to 204
Data columns (total 26 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   symboling               205 non-null    int64
 1   fueltype                205 non-null    object
 2   aspiration              205 non-null    object
 3   doornumber              205 non-null    object
 4   drivewheel              205 non-null    object
 5   enginelocation          205 non-null    object
 6   wheelbase               205 non-null    float64
 7   carlength               205 non-null    float64
 8   carwidth                205 non-null    float64
 9   carheight               205 non-null    float64
 10  curbweight              205 non-null    int64
 11  enginetype              205 non-null    object
 12  cylindernumber          205 non-null    object
 13  enginesize              205 non-null    int64
 14  fuelsystem              205 non-null    object
 15  boreratio               205 non-null    float64
 16  stroke                  205 non-null    float64
 17  compressionratio        205 non-null    float64
 18  horsepower              205 non-null    int64
 19  peakrpm                 205 non-null    int64
 20  citympg                 205 non-null    int64
 21  highwaympg              205 non-null    int64
 22  price                   205 non-null    float64
 23  fueltype_gas/diesel     205 non-null    int64
 24  aspiration_std/turbo    205 non-null    int64
 25  drivewheel_rwd/fwd/4wd  205 non-null    int64
dtypes: float64(8), int64(10), object(8)
memory usage: 41.8+ KB

In [16]:
X = df[["fueltype_gas/diesel"]]

In [17]:
Y = df[["curbweight"]]

In [18]:
X_train, X_test, Y_train, Y_test = train_test_split(X,Y, test_size=0.2, random_state=42)

In [19]:
from sklearn import linear_model

In [20]:
lin_model = linear_model.LinearRegression()

In [21]:
lin_model.fit(X_train, Y_train)

LinearRegression()

In [22]:
fuel_type = 1

In [23]:
predicted_curbweight = lin_model.predict([[fuel_type]])

/Users/shobhitkhinvasara/.conda/envs/intro_ml/lib/python3.11/site-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

In [24]:
print(predicted_curbweight)

[[2845.33333333]]